const express = require('express');
const multer = require('multer');
const { exiftool } = require('exiftool-vendored');
const fs = require('fs');
const path = require('path');
const os = require('os');

const app = express();
const port = process.env.PORT || 3000;
const upload = multer({ storage: multer.memoryStorage() });

app.use(express.static(path.join(__dirname, 'public')));

app.post('/api/extract', upload.single('file'), async (req, res) => {
    if (!req.file) return res.status(400).json({ error: 'No file' });
    const tempPath = path.join(os.tmpdir(), `scan-${Date.now()}`);
    try {
        fs.writeFileSync(tempPath, req.file.buffer);
        const metadata = await exiftool.read(tempPath, ["-n"]);
        if (fs.existsSync(tempPath)) fs.unlinkSync(tempPath);
        
        const captureDate = metadata.DateTimeOriginal || metadata.CreateDate || metadata.DateCreated;
        const software = (metadata.Software || metadata.CreatorTool || "").toLowerCase();
        const lat = metadata.GPSLatitude || (metadata.Composite && metadata.Composite.GPSLatitude);

        let humanSummary = "SCANNED. ";
        if (software.includes('photoshop') || software.includes('canva') || software.includes('gimp')) {
            humanSummary = "⚠️ ALERT: This photo has been edited in a software program like Photoshop or Canva.";
        } else if (software.includes('midjourney') || software.includes('dall-e') || JSON.stringify(metadata).toLowerCase().includes('ai')) {
            humanSummary = "🤖 AI DETECTED: This image appears to have been generated by an Artificial Intelligence.";
        } else if (!captureDate && !lat) {
            humanSummary = "📵 STRIPPED: An app like WhatsApp or Instagram deleted the hidden information to protect privacy. We can't see when or where this was taken.";
        } else {
            humanSummary = "✅ ORIGINAL: This photo looks like a real, unedited file taken directly from a camera.";
        }

        res.json({
            ...metadata,
            display_captured: captureDate ? captureDate.toString() : null,
            display_edited: metadata.ModifyDate ? metadata.ModifyDate.toString() : null,
            display_summary: humanSummary,
            gps: (lat && metadata.GPSLongitude) ? { lat: parseFloat(lat), lon: parseFloat(metadata.GPSLongitude) } : null
        });
    } catch (e) { res.status(500).json({ error: 'Scan failed' }); }
});

app.get('/', (req, res) => {
    const indexPath = path.join(__dirname, 'public', 'index.html');
    if (fs.existsSync(indexPath)) res.sendFile(indexPath);
    else res.status(404).send("index.html missing");
});

app.listen(port, () => console.log(`System Online`));
